DROP TABLE IF EXISTS ACCOUNT;

CREATE TABLE ACCOUNT (
  account_no BIGINT PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  branch VARCHAR(250) NOT NULL,
  account_type VARCHAR(250) NOT NULL,
  address VARCHAR(250) DEFAULT NULL,
  balance NUMERIC
);